### ISSUE TITLE
APIs get jobStatus ERROR, although jobs started, initiated and run

### ISSUE THREAD

**Issue by oschwengers** [ag-computational-bio/bakta-web-backend#18]
Initially filed by @cuongngh in https://github.com/oschwengers/bakta/issues/316:

> Dear Bakta team,
> 
> I tried to use the api as the background for my app. I got strange error and the jobs stopped. I did check the status of the jobs, and the jobs were initiated, started and run. But after about 40 second, I got the status ERROR. I am sure that my script is fine. Do you know what should be the reason for that? Is that due to the connection, or due to the APIs. I do not know how to fix this problem. I check manually the job on Bakta website, and there is not problem regarding the data, format ... The job finished successfully, but when I run by APIs. It always turns out the ERROR.
> 
> Thanks a lot for the help.

**Comment by St4NNi** [comment]
Hi @cuongngh, 

The backend still needs some improvements in terms of error handling, this is in preparation and will hopefully come soon. 

Your problem boils down to a missing file upload (`artifact replicons failed to load`),  currently all files are required even if they are not used. So you need to do a PUT request to all three pre-authenticated S3 urls for 
- `fastadata.fasta`
- `replicons.tsv`
- `prodigal.tf`

If you do not have the relevant data, you can simply issue a PUT request with an empty body. This is a constraint of the underlying infrastructure that safeguards that all possible files are provided. We may improve this in the future to make all non `.fasta` files optional.

Hope this helps !

**Comment by cuongngh** [comment]
> Hi @cuongngh,
> 
> The backend still needs some improvements in terms of error handling, this is in preparation and will hopefully come soon.
> 
> Your problem boils down to a missing file upload (`artifact replicons failed to load`), currently all files are required even if they are not used. So you need to do a PUT request to all three pre-authenticated S3 urls for
> 
> * `fastadata.fasta`
> * `replicons.tsv`
> * `prodigal.tf`
> 
> If you do not have the relevant data, you can simply issue a PUT request with an empty body. This is a constraint of the underlying infrastructure that safeguards that all possible files are provided. We may improve this in the future to make all non `.fasta` files optional.
> 
> Hope this helps !

Hi St4NNi, in fact I did upload files from my script. Because I printed out if the uploading fails. I control the uploading. The only point is that I want to catch the status of the job with "SUCCESSFUL", so that the links to result files will be valid. 
Thanks a lot for the help.

**Comment by St4NNi** [comment]
I hope this fixes the issue, will close the issue feel free to comment if you need additional help.

**Comment by cuongngh** [comment]
Hi @St4NNi , in fact I did not solve the problem so far. Follow your suggestions, I just want to confirm that I uploaded the fasta file. Thanks for your efforts. And if you have any idea how to fix this, I would be very appreciated for that.

**Comment by St4NNi** [comment]
Sorry, I must have misread your post. Just to be clear, you need to upload **all** three files before you can start the job. Maybe it would be a good idea (if possible) to share your code so I can take a look at it and see what might be wrong.

**Comment by cuongngh** [comment]
> Sorry, I must have misread your post. Just to be clear, you need to upload **all** three files before you can start the job. Maybe it would be a good idea (if possible) to share your code so I can take a look at it and see what might be wrong.

Hi @St4NNi, okie, I will try to follow this. Cheers.

**Comment by cuongngh** [comment]
> Sorry, I must have misread your post. Just to be clear, you need to upload **all** three files before you can start the job. Maybe it would be a good idea (if possible) to share your code so I can take a look at it and see what might be wrong.

I tried to upload three files. But it failed at some points of time. If it possible, please tell me where I can share the script with you. Thanks in advance.

**Comment by cuongngh** [comment]
> Hi, this looks better now and seems to result in a different error, skimming through the logs I have found the following Bakta error: `ERROR: wrong 'plasmid' name! Plasmid names must either be named as 'unnamed', 'unnamed1', ... or start with a lower 'p', contain only digits, dots, underscores and letters, and are limited to 20 characters in total.`
> 
> So it seems like you have an invalid name for the plasmid(s) you have specified. Depending on the size of your script you could eiter upload it somewehere (for example a dedicated git repo) and share it there, or you could use the code block feature in your comment directly using three (´´´) backticks

Hi, thanks for response. Regarding your comments, I used both with my script and the online tool of Bakta. And I named them as required by Bakta. I will try to share the script with you. It is not too long.

**Comment by cuongngh** [comment]
> Hi, this looks better now and seems to result in a different error, skimming through the logs I have found the following Bakta error: `ERROR: wrong 'plasmid' name! Plasmid names must either be named as 'unnamed', 'unnamed1', ... or start with a lower 'p', contain only digits, dots, underscores and letters, and are limited to 20 characters in total.`
> 
> So it seems like you have an invalid name for the plasmid(s) you have specified. Depending on the size of your script you could eiter upload it somewehere (for example a dedicated git repo) and share it there, or you could use the code block feature in your comment directly using three (´´´) backticks

@St4NNi, I have shared a script with you from Git. Could you please help me? Thanks a lot in advance.

**Comment by St4NNi** [comment]
The last update was that this is working now. So I am closing this issue, if you have any additional problems: 
Feel free to open a new issue.
