### ISSUE TITLE
Fail if strain and co. contain whitespaces

### ISSUE THREAD

**Issue by St4NNi** [ag-computational-bio/bakta-web-backend#20]
Bakta web execution fails if strain, genus and co. contain whitespaces. We should sanitize this in both front- and backend.

**Comment by lukasjelonek** [comment]
Wouldn't it be better to quote the strings that contain whitespaces instead of removing these? Or does bakta in general not work with whitespaces in these fields?

**Comment by St4NNi** [comment]
Yes this might be an even better idea. I will give it a try and only sanitize for quotes.

**Comment by lukasjelonek** [comment]
I think the simplest way will be to use single quotes, so the shell won't do any interpolation and you will only have to escape the `'`-character.

**Comment by St4NNi** [comment]
Implemented and tested in https://github.com/ag-computational-bio/bakta-web-backend/commit/32f44ac334a430c3383ed1334e2185446f709bde
